# SPDX-License-Identifier: AGPL-3.0-or-later

#!/usr/bin/env python3
"""
healthSpring Exp023 — Multi-Channel Biosignal Fusion (ECG + PPG + EDA)

Validates fusion of ECG (Pan-Tompkins), PPG (SpO2), and EDA (SCR) channels
into a unified health assessment with stress index and overall score.

Baseline is generated by running the Rust exp023_biosignal_fusion binary
with --write-baseline (uses Rust synthetic generators for consistency).

Provenance:
  Baseline source: Rust exp023_biosignal_fusion --write-baseline
  Command:         python3 control/biosignal/exp023_fusion.py
"""

import json
import os
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
BASELINE_PATH = os.path.join(SCRIPT_DIR, "exp023_baseline.json")


def main():
    print("=" * 72)
    print("healthSpring Exp023: Multi-Channel Biosignal Fusion (ECG + PPG + EDA)")
    print("  Running Rust binary to generate baseline...")
    print("=" * 72)

    # Run Rust binary with --write-baseline to create exp023_baseline.json
    result = subprocess.run(
        ["cargo", "run", "--bin", "exp023_biosignal_fusion", "--", "--write-baseline"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        print(result.stdout, file=sys.stderr)
        sys.exit(1)

    print(result.stdout)

    # Add provenance to the baseline
    if not os.path.exists(BASELINE_PATH):
        print(f"ERROR: Baseline not created at {BASELINE_PATH}", file=sys.stderr)
        sys.exit(1)

    with open(BASELINE_PATH, "r") as f:
        data = json.load(f)

    # Get git commit
    git_result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    git_commit = git_result.stdout.strip() if git_result.returncode == 0 else "unknown"

    data["_provenance"]["python"] = sys.version
    data["_provenance"]["git_commit"] = git_commit
    data["_provenance"]["command"] = "python3 control/biosignal/exp023_fusion.py"
    data["_provenance"]["script"] = "control/biosignal/exp023_fusion.py"

    with open(BASELINE_PATH, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")

    print(f"\nBaseline written to {BASELINE_PATH} (with provenance)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
