# SPDX-License-Identifier: AGPL-3.0-only

#!/usr/bin/env python3
"""
healthSpring Exp022 — PPG SpO2 R-value Calibration

Validates PPG-based SpO2 estimation:
- R-value = (AC_red/DC_red) / (AC_ir/DC_ir)
- SpO2 = 110 - 25*R (standard calibration)
- Synthetic PPG generation and roundtrip

Baseline is generated by running the Rust exp022_ppg_spo2 binary
with --write-baseline (uses Rust synthetic PPG generator for consistency).

Provenance:
  Baseline source: Rust exp022_ppg_spo2 --write-baseline
  Command:         python3 control/biosignal/exp022_ppg_spo2.py
"""

import json
import os
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
BASELINE_PATH = os.path.join(SCRIPT_DIR, "exp022_baseline.json")


def main():
    print("=" * 72)
    print("healthSpring Exp022: PPG SpO2 R-value Calibration")
    print("  Running Rust binary to generate baseline...")
    print("=" * 72)

    # Run Rust binary with --write-baseline to create exp022_baseline.json
    result = subprocess.run(
        ["cargo", "run", "--bin", "exp022_ppg_spo2", "--", "--write-baseline"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        print(result.stdout, file=sys.stderr)
        sys.exit(1)

    print(result.stdout)

    # Add provenance to the baseline
    if not os.path.exists(BASELINE_PATH):
        print(f"ERROR: Baseline not created at {BASELINE_PATH}", file=sys.stderr)
        sys.exit(1)

    with open(BASELINE_PATH, "r") as f:
        data = json.load(f)

    # Get git commit
    git_result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    git_commit = git_result.stdout.strip() if git_result.returncode == 0 else "unknown"

    data["_provenance"]["python"] = sys.version
    data["_provenance"]["git_commit"] = git_commit
    data["_provenance"]["command"] = "python3 control/biosignal/exp022_ppg_spo2.py"
    data["_provenance"]["script"] = "control/biosignal/exp022_ppg_spo2.py"

    with open(BASELINE_PATH, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")

    print(f"\nBaseline written to {BASELINE_PATH} (with provenance)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
