// SPDX-License-Identifier: AGPL-3.0-or-later
//! Provenance records for infrastructure, validation, and composition tracks (Tracks 6–10).
//!
//! Discovery, Validation, Scripts, Toxicology, Simulation, GPU parity,
//! composition validation, and demo experiment records.

use super::ProvenanceRecord;

pub(super) const RECORDS: &[ProvenanceRecord] = &[
    // Track 6: Discovery
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp090",
        python_script: "control/discovery/exp090_matrix_scoring.py",
        python_version: "3.10+",
        description: "Anderson-augmented MATRIX drug repurposing scoring",
        checks: 15,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp090_matrix_scoring.py",
        baseline_source: "Fajgenbaum DC et al. NEJM 379:1941 (MATRIX pathway × geometry × disorder)",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp091",
        python_script: "control/discovery/exp091_addrc_hts.py",
        python_version: "3.10+",
        description: "ADDRC high-throughput screening analysis (Z', SSMD)",
        checks: 12,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp091_addrc_hts.py",
        baseline_source: "Zhang 1999 J Biomol Screen 4:67 doi:10.1177/108705719900400206 (Z'-factor); SSMD",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp092",
        python_script: "control/discovery/exp092_compound_library.py",
        python_version: "3.10+",
        description: "ADDRC compound library batch IC50 profiling",
        checks: 12,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp092_compound_library.py",
        baseline_source: "Hill 1910 J Physiol doi:10.1113/jphysiol.1910.sp001397 (IC50, selectivity index)",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp093",
        python_script: "control/discovery/exp093_chembl_jak_panel.py",
        python_version: "3.10+",
        description: "ChEMBL JAK inhibitor selectivity panel",
        checks: 15,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp093_chembl_jak_panel.py",
        baseline_source: "ChEMBL database; oclacitinib/tofacitinib/ruxolitinib/baricitinib IC50s",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp094",
        python_script: "control/discovery/exp094_rho_mrtf_fibrosis.py",
        python_version: "3.10+",
        description: "Rho/MRTF/SRF fibrosis scoring baseline",
        checks: 14,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp094_rho_mrtf_fibrosis.py",
        baseline_source: "Haak 2014 JPET 349:480 doi:10.1124/jpet.114.213520 (CCG-1423, CCG-203971)",
    },
    // Track 7: Validation
    ProvenanceRecord {
        track: "validation",
        experiment: "exp040",
        python_script: "control/validation/exp040_barracuda_cpu.py",
        python_version: "3.10+",
        description: "barraCuda CPU parity analytical baselines",
        checks: 15,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/validation/exp040_barracuda_cpu.py",
        baseline_source: "Analytical identities (Hill, AUC, diversity, C0=Dose/Vd)",
    },
    // Track 8: Scripts
    ProvenanceRecord {
        track: "scripts",
        experiment: "bench_barracuda",
        python_script: "control/scripts/bench_barracuda_cpu_vs_python.py",
        python_version: "3.10+",
        description: "barraCuda CPU vs Python benchmark timing",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/scripts/bench_barracuda_cpu_vs_python.py",
        baseline_source: "Benchmark timing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "bench_v16",
        python_script: "control/scripts/bench_v16_cpu_vs_python.py",
        python_version: "3.10+",
        description: "V16 CPU parity benchmarks (Python baseline)",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/scripts/bench_v16_cpu_vs_python.py",
        baseline_source: "Benchmark timing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "compare_v16",
        python_script: "control/scripts/compare_v16_benchmarks.py",
        python_version: "3.10+",
        description: "Rust CPU vs Python benchmark comparison",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/scripts/compare_v16_benchmarks.py",
        baseline_source: "Benchmark comparison (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp085",
        python_script: "control/scripts/control_exp085_gpu_scaling.py",
        python_version: "3.10+",
        description: "GPU scaling validation (Python control)",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/scripts/control_exp085_gpu_scaling.py",
        baseline_source: "GPU scaling validation (Amdahl/Gustafson theoretical bounds)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "tolerances",
        python_script: "control/tolerances.py",
        python_version: "3.10+",
        description: "Centralized tolerance constants (Python mirror of tolerances.rs)",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/tolerances.py",
        baseline_source: "Tolerance constant definitions (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "update_provenance",
        python_script: "control/update_provenance.py",
        python_version: "3.10+",
        description: "Update baseline JSON files with provenance metadata",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/update_provenance.py",
        baseline_source: "Metadata utility (no validation targets)",
    },
    // Track 9: Low-Affinity Binding / Toxicology / Simulation
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp097",
        python_script: "control/discovery/exp097_affinity_landscape.py",
        python_version: "3.10+",
        description: "Low-affinity binding: composite score, selectivity, Gini breadth",
        checks: 18,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/discovery/exp097_affinity_landscape.py",
        baseline_source: "Hill 1910 (fractional occupancy); Lorenz/Gini (inequality metrics)",
    },
    ProvenanceRecord {
        track: "toxicology",
        experiment: "exp098",
        python_script: "control/toxicology/exp098_toxicity_landscape.py",
        python_version: "3.10+",
        description: "Toxicity landscape: systemic burden, IPR, clearance, delocalization",
        checks: 15,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/toxicology/exp098_toxicity_landscape.py",
        baseline_source: "Anderson 1958 (IPR/localization); Rowland & Tozer (clearance kinetics)",
    },
    ProvenanceRecord {
        track: "toxicology",
        experiment: "exp099",
        python_script: "control/toxicology/exp099_hormesis.py",
        python_version: "3.10+",
        description: "Hormesis: biphasic dose-response, mithridatism, caloric restriction",
        checks: 27,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/toxicology/exp099_hormesis.py",
        baseline_source: "Calabrese & Baldwin 2003 (hormesis); Mattson & Calabrese 2010",
    },
    ProvenanceRecord {
        track: "simulation",
        experiment: "exp111",
        python_script: "control/simulation/exp111_causal_terrarium.py",
        python_version: "3.10+",
        description: "Causal terrarium: mechanistic fitness, population dynamics, ecosystem",
        checks: 18,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/simulation/exp111_causal_terrarium.py",
        baseline_source: "Lotka-Volterra (population dynamics); HSP/SOD/p53/mTOR (pathway biology)",
    },
    // ── Diagnostic / Clinical Pipeline (Rust analytical — no Python control) ──
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp050",
        python_script: "",
        python_version: "",
        description: "Diagnostic pipeline: patient assessment → composite risk",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: ValidationHarness checks against lib-computed values",
    },
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp051",
        python_script: "",
        python_version: "",
        description: "Population diagnostic Monte Carlo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: population statistics against bounded ranges",
    },
    // ── GPU / Compute Experiments (bench/parity — no Python baseline) ──
    ProvenanceRecord {
        track: "validation",
        experiment: "exp053",
        python_script: "",
        python_version: "",
        description: "GPU parity: Hill/PopPK/Diversity CPU vs GPU",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU fallback as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp054",
        python_script: "",
        python_version: "",
        description: "GPU fused pipeline validation",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU sequential as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp055",
        python_script: "",
        python_version: "",
        description: "GPU scaling validation (Amdahl/Gustafson bounds)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Theoretical: Amdahl's law + Gustafson's law scaling bounds",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp060",
        python_script: "",
        python_version: "",
        description: "CPU vs GPU pipeline comparative benchmark",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU path as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp062",
        python_script: "",
        python_version: "",
        description: "PCIe transfer validation (bandwidth bounds)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Theoretical: PCIe Gen3/4/5 bandwidth limits",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp067",
        python_script: "",
        python_version: "",
        description: "GPU parity extended (V16 trio + Tier B ops)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU fallback as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp083",
        python_script: "",
        python_version: "",
        description: "GPU V16 parity (MM/SCFA/BeatClassify CPU vs GPU)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU fallback as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp084",
        python_script: "",
        python_version: "",
        description: "V16 CPU parity benchmarks",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Benchmark: CPU timing comparison (no validation targets)",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp086",
        python_script: "",
        python_version: "",
        description: "ToadStool V16 dispatch matrix",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Integration: toadStool compute.dispatch.submit round-trip",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp087",
        python_script: "",
        python_version: "",
        description: "Mixed NUCLEUS V16 dispatch (CPU+GPU+NPU)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Integration: metalForge substrate selection + dispatch",
    },
    // ── IPC / Dashboard / Visualization (demo — no Python baseline) ──
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp052",
        python_script: "",
        python_version: "",
        description: "petalTongue render integration demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: petalTongue visualization.render IPC (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp056",
        python_script: "",
        python_version: "",
        description: "Study scenario dump for whitePaper baseCamp",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: scenario generation (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp061",
        python_script: "",
        python_version: "",
        description: "Mixed hardware dispatch demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: metalForge hardware dispatch (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp063",
        python_script: "",
        python_version: "",
        description: "Clinical TRT scenario explorer",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: clinical scenario generation (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp064",
        python_script: "",
        python_version: "",
        description: "IPC push integration demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: petalTongue IPC push (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp065",
        python_script: "",
        python_version: "",
        description: "Live dashboard visualization demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: live scenario dashboard (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp066",
        python_script: "",
        python_version: "",
        description: "barraCuda CPU benchmark suite",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Benchmark: CPU timing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp068",
        python_script: "",
        python_version: "",
        description: "GPU benchmark suite",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Benchmark: GPU timing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp069",
        python_script: "",
        python_version: "",
        description: "ToadStool dispatch matrix demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: toadStool dispatch routing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp070",
        python_script: "",
        python_version: "",
        description: "PCIe P2P bypass validation",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Integration: PCIe P2P transfer (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp071",
        python_script: "",
        python_version: "",
        description: "Mixed system pipeline demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: multi-substrate pipeline (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp072",
        python_script: "",
        python_version: "",
        description: "Compute dashboard visualization",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: compute metrics dashboard (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp073",
        python_script: "",
        python_version: "",
        description: "Clinical TRT dashboard demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: TRT clinical dashboard (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp074",
        python_script: "",
        python_version: "",
        description: "Interaction roundtrip IPC validation",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Integration: JSON-RPC roundtrip determinism",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp076",
        python_script: "",
        python_version: "",
        description: "Full pipeline scenario composition",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: end-to-end pipeline scenario (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp088",
        python_script: "",
        python_version: "",
        description: "Unified dashboard visualization",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: unified dashboard (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp089",
        python_script: "",
        python_version: "",
        description: "Patient explorer interactive demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: interactive patient explorer (no validation targets)",
    },
    // ── Discovery / Comparative (science with analytical baselines) ──
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp095",
        python_script: "",
        python_version: "",
        description: "iPSC skin model fibrosis scoring",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: fibrosis pathway geometry + Anderson disorder scoring",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp096",
        python_script: "",
        python_version: "",
        description: "Niclosamide nanoparticle delivery model",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: drug delivery PK kinetics",
    },
    // ── QS / Real-Data / WFDB Experiments ──
    ProvenanceRecord {
        track: "microbiome",
        experiment: "exp107",
        python_script: "",
        python_version: "",
        description: "QS-augmented Anderson localization",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: QS gene profile → Anderson disorder coupling",
    },
    ProvenanceRecord {
        track: "microbiome",
        experiment: "exp108",
        python_script: "",
        python_version: "",
        description: "Real 16S Anderson diversity (HMP/Schubert public data)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "HMP2 16S (SRA: PRJNA275349); Schubert 2014 mBio 5:e01021-14",
    },
    ProvenanceRecord {
        track: "biosignal",
        experiment: "exp109",
        python_script: "",
        python_version: "",
        description: "MIT-BIH arrhythmia WFDB validation",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "MIT-BIH Arrhythmia Database (PhysioNet DOI:10.13026/C2F305)",
    },
    ProvenanceRecord {
        track: "comparative",
        experiment: "exp110",
        python_script: "",
        python_version: "",
        description: "Equine laminitis PK model",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: equine NSAID PK and laminitis biomarkers",
    },
    // ── NLME / Pipeline (science with analytical baselines) ──
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp075",
        python_script: "",
        python_version: "",
        description: "NLME cross-validation (FOCE/SAEM parameter recovery)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: NLME parameter recovery against known population PK model",
    },
    // ── Composition Validation (Tier 4 — Rust dispatch parity) ──
    ProvenanceRecord {
        track: "validation",
        experiment: "exp112",
        python_script: "",
        python_version: "",
        description: "Composition validation: PK/PD dispatch parity",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: dispatch_science vs direct Rust call determinism",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp113",
        python_script: "",
        python_version: "",
        description: "Composition validation: microbiome dispatch parity",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: dispatch_science vs direct Rust call determinism",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp114",
        python_script: "",
        python_version: "",
        description: "Composition validation: health triad + registry surface",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: registered_capabilities coverage and dispatch completeness",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp115",
        python_script: "",
        python_version: "",
        description: "Composition validation: proto-nucleate alignment",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: socket conventions, capability list, PRIMAL_NAME/DOMAIN",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp116",
        python_script: "",
        python_version: "",
        description: "Composition validation: provenance session lifecycle",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: data session begin/record/complete + trio probe",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp117",
        python_script: "",
        python_version: "",
        description: "Composition validation: IPC round-trip + proto-nucleate alias fidelity",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: JSON-RPC wire protocol round-trip determinism",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp118",
        python_script: "",
        python_version: "",
        description: "Composition validation: deploy graph vs proto-nucleate alignment (Tier 5)",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-11",
        exact_command: "",
        baseline_source: "Composition: TOML graph structure, fragments, bonding, capability coverage",
    },
    ProvenanceRecord {
        track: "composition",
        experiment: "exp119",
        python_script: "",
        python_version: "",
        description: "Composition parity: live IPC science dispatch vs local Rust (Tier 4)",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-17",
        exact_command: "",
        baseline_source: "Composition: IPC JSON-RPC results vs direct Rust function calls",
    },
    ProvenanceRecord {
        track: "composition",
        experiment: "exp120",
        python_script: "",
        python_version: "",
        description: "Composition provenance: live trio round-trip via IPC (Tier 4)",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-17",
        exact_command: "",
        baseline_source: "Composition: provenance trio session lifecycle over IPC",
    },
    ProvenanceRecord {
        track: "composition",
        experiment: "exp121",
        python_script: "",
        python_version: "",
        description: "Composition health triad: liveness/readiness/capability.list via IPC (Tier 4)",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-17",
        exact_command: "",
        baseline_source: "Composition: NUCLEUS health probes over live JSON-RPC",
    },
    ProvenanceRecord {
        track: "composition",
        experiment: "exp122",
        python_script: "",
        python_version: "",
        description: "Level 5 primal proof: barraCuda ecobin IPC vs library parity (stats.mean, stats.std_dev, rng.uniform)",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-17",
        exact_command: "",
        baseline_source: "Primal proof: barraCuda wire-ready methods over JSON-RPC UDS",
    },
];
