// SPDX-License-Identifier: AGPL-3.0-or-later
//! Provenance records for Track 6: Discovery experiments (exp090–096).

use super::ProvenanceRecord;

pub(super) const RECORDS: &[ProvenanceRecord] = &[
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp090",
        python_script: "control/discovery/exp090_matrix_scoring.py",
        python_version: "3.10+",
        description: "Anderson-augmented MATRIX drug repurposing scoring",
        checks: 15,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp090_matrix_scoring.py",
        baseline_source: "Fajgenbaum DC et al. NEJM 379:1941 (MATRIX pathway × geometry × disorder)",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp091",
        python_script: "control/discovery/exp091_addrc_hts.py",
        python_version: "3.10+",
        description: "ADDRC high-throughput screening analysis (Z', SSMD)",
        checks: 12,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp091_addrc_hts.py",
        baseline_source: "Zhang 1999 J Biomol Screen 4:67 doi:10.1177/108705719900400206 (Z'-factor); SSMD",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp092",
        python_script: "control/discovery/exp092_compound_library.py",
        python_version: "3.10+",
        description: "ADDRC compound library batch IC50 profiling",
        checks: 12,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp092_compound_library.py",
        baseline_source: "Hill 1910 J Physiol doi:10.1113/jphysiol.1910.sp001397 (IC50, selectivity index)",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp093",
        python_script: "control/discovery/exp093_chembl_jak_panel.py",
        python_version: "3.10+",
        description: "ChEMBL JAK inhibitor selectivity panel",
        checks: 15,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp093_chembl_jak_panel.py",
        baseline_source: "ChEMBL database; oclacitinib/tofacitinib/ruxolitinib/baricitinib IC50s",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp094",
        python_script: "control/discovery/exp094_rho_mrtf_fibrosis.py",
        python_version: "3.10+",
        description: "Rho/MRTF/SRF fibrosis scoring baseline",
        checks: 14,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp094_rho_mrtf_fibrosis.py",
        baseline_source: "Haak 2014 JPET 349:480 doi:10.1124/jpet.114.213520 (CCG-1423, CCG-203971)",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp095",
        python_script: "",
        python_version: "",
        description: "iPSC skin model fibrosis scoring",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: fibrosis pathway geometry + Anderson disorder scoring",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp096",
        python_script: "",
        python_version: "",
        description: "Niclosamide nanoparticle delivery model",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: drug delivery PK kinetics",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp097",
        python_script: "control/discovery/exp097_affinity_landscape.py",
        python_version: "3.10+",
        description: "Low-affinity binding: composite score, selectivity, Gini breadth",
        checks: 18,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/discovery/exp097_affinity_landscape.py",
        baseline_source: "Hill 1910 (fractional occupancy); Lorenz/Gini (inequality metrics)",
    },
];
