// SPDX-License-Identifier: AGPL-3.0-or-later
//! Provenance records for GPU parity and compute benchmark experiments.

use super::ProvenanceRecord;

pub(super) const RECORDS: &[ProvenanceRecord] = &[
    ProvenanceRecord {
        track: "validation",
        experiment: "exp053",
        python_script: "",
        python_version: "",
        description: "GPU parity: Hill/PopPK/Diversity CPU vs GPU",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU fallback as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp054",
        python_script: "",
        python_version: "",
        description: "GPU fused pipeline validation",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU sequential as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp055",
        python_script: "",
        python_version: "",
        description: "GPU scaling validation (Amdahl/Gustafson bounds)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Theoretical: Amdahl's law + Gustafson's law scaling bounds",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp060",
        python_script: "",
        python_version: "",
        description: "CPU vs GPU pipeline comparative benchmark",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU path as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp062",
        python_script: "",
        python_version: "",
        description: "PCIe transfer validation (bandwidth bounds)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Theoretical: PCIe Gen3/4/5 bandwidth limits",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp067",
        python_script: "",
        python_version: "",
        description: "GPU parity extended (V16 trio + Tier B ops)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU fallback as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp083",
        python_script: "",
        python_version: "",
        description: "GPU V16 parity (MM/SCFA/BeatClassify CPU vs GPU)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU fallback as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp084",
        python_script: "",
        python_version: "",
        description: "V16 CPU parity benchmarks",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Benchmark: CPU timing comparison (no validation targets)",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp085",
        python_script: "",
        python_version: "",
        description: "GPU vs CPU V16 scaling benchmark",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Benchmark: GPU scaling (no validation targets)",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp086",
        python_script: "",
        python_version: "",
        description: "ToadStool V16 dispatch matrix",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Integration: toadStool compute.dispatch.submit round-trip",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp087",
        python_script: "",
        python_version: "",
        description: "Mixed NUCLEUS V16 dispatch (CPU+GPU+NPU)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Integration: metalForge substrate selection + dispatch",
    },
];
