// SPDX-License-Identifier: AGPL-3.0-or-later
//! Provenance records for validation, scripts, toxicology, simulation,
//! diagnostic, NLME, QS/real-data, and comparative experiments.
//!
//! Discovery records live in `records_discovery.rs`, GPU in `records_gpu.rs`,
//! and composition in `records_composition.rs`.

use super::ProvenanceRecord;

pub(super) const RECORDS: &[ProvenanceRecord] = &[
    // Track 7: Validation
    ProvenanceRecord {
        track: "validation",
        experiment: "exp040",
        python_script: "control/validation/exp040_barracuda_cpu.py",
        python_version: "3.10+",
        description: "barraCuda CPU parity analytical baselines",
        checks: 15,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/validation/exp040_barracuda_cpu.py",
        baseline_source: "Analytical identities (Hill, AUC, diversity, C0=Dose/Vd)",
    },
    // Track 8: Scripts & Benchmarks
    ProvenanceRecord {
        track: "scripts",
        experiment: "bench_barracuda",
        python_script: "control/scripts/bench_barracuda_cpu_vs_python.py",
        python_version: "3.10+",
        description: "barraCuda CPU vs Python benchmark timing",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/scripts/bench_barracuda_cpu_vs_python.py",
        baseline_source: "Benchmark timing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "bench_v16",
        python_script: "control/scripts/bench_v16_cpu_vs_python.py",
        python_version: "3.10+",
        description: "V16 CPU parity benchmarks (Python baseline)",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/scripts/bench_v16_cpu_vs_python.py",
        baseline_source: "Benchmark timing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "compare_v16",
        python_script: "control/scripts/compare_v16_benchmarks.py",
        python_version: "3.10+",
        description: "Rust CPU vs Python benchmark comparison",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/scripts/compare_v16_benchmarks.py",
        baseline_source: "Benchmark comparison (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp085",
        python_script: "control/scripts/control_exp085_gpu_scaling.py",
        python_version: "3.10+",
        description: "GPU scaling validation (Python control)",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/scripts/control_exp085_gpu_scaling.py",
        baseline_source: "GPU scaling validation (Amdahl/Gustafson theoretical bounds)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "tolerances",
        python_script: "control/tolerances.py",
        python_version: "3.10+",
        description: "Centralized tolerance constants (Python mirror of tolerances.rs)",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/tolerances.py",
        baseline_source: "Tolerance constant definitions (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "update_provenance",
        python_script: "control/update_provenance.py",
        python_version: "3.10+",
        description: "Update baseline JSON files with provenance metadata",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/update_provenance.py",
        baseline_source: "Metadata utility (no validation targets)",
    },
    // Track 9: Toxicology & Simulation
    ProvenanceRecord {
        track: "toxicology",
        experiment: "exp098",
        python_script: "control/toxicology/exp098_toxicity_landscape.py",
        python_version: "3.10+",
        description: "Toxicity landscape: systemic burden, IPR, clearance, delocalization",
        checks: 15,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/toxicology/exp098_toxicity_landscape.py",
        baseline_source: "Anderson 1958 (IPR/localization); Rowland & Tozer (clearance kinetics)",
    },
    ProvenanceRecord {
        track: "toxicology",
        experiment: "exp099",
        python_script: "control/toxicology/exp099_hormesis.py",
        python_version: "3.10+",
        description: "Hormesis: biphasic dose-response, mithridatism, caloric restriction",
        checks: 27,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/toxicology/exp099_hormesis.py",
        baseline_source: "Calabrese & Baldwin 2003 (hormesis); Mattson & Calabrese 2010",
    },
    ProvenanceRecord {
        track: "simulation",
        experiment: "exp111",
        python_script: "control/simulation/exp111_causal_terrarium.py",
        python_version: "3.10+",
        description: "Causal terrarium: mechanistic fitness, population dynamics, ecosystem",
        checks: 18,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/simulation/exp111_causal_terrarium.py",
        baseline_source: "Lotka-Volterra (population dynamics); HSP/SOD/p53/mTOR (pathway biology)",
    },
    // Diagnostic / Clinical Pipeline (Rust analytical)
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp050",
        python_script: "",
        python_version: "",
        description: "Diagnostic pipeline: patient assessment → composite risk",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: ValidationHarness checks against lib-computed values",
    },
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp051",
        python_script: "",
        python_version: "",
        description: "Population diagnostic Monte Carlo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: population statistics against bounded ranges",
    },
    // IPC / Dashboard / Visualization demos
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp052",
        python_script: "",
        python_version: "",
        description: "petalTongue render integration demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: petalTongue visualization.render IPC (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp056",
        python_script: "",
        python_version: "",
        description: "Study scenario dump for whitePaper baseCamp",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: scenario generation (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp061",
        python_script: "",
        python_version: "",
        description: "Mixed hardware dispatch demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: metalForge hardware dispatch (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp063",
        python_script: "",
        python_version: "",
        description: "Clinical TRT scenario explorer",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: clinical scenario generation (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp064",
        python_script: "",
        python_version: "",
        description: "IPC push integration demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: petalTongue IPC push (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp065",
        python_script: "",
        python_version: "",
        description: "Live dashboard visualization demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: live scenario dashboard (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp066",
        python_script: "",
        python_version: "",
        description: "barraCuda CPU benchmark suite",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Benchmark: CPU timing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp068",
        python_script: "",
        python_version: "",
        description: "GPU benchmark suite",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Benchmark: GPU timing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp069",
        python_script: "",
        python_version: "",
        description: "ToadStool dispatch matrix demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: toadStool dispatch routing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp070",
        python_script: "",
        python_version: "",
        description: "PCIe P2P bypass validation",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Integration: PCIe P2P transfer (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp071",
        python_script: "",
        python_version: "",
        description: "Mixed system pipeline demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: multi-substrate pipeline (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp072",
        python_script: "",
        python_version: "",
        description: "Compute dashboard visualization",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: compute metrics dashboard (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp073",
        python_script: "",
        python_version: "",
        description: "Clinical TRT dashboard demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: TRT clinical dashboard (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp074",
        python_script: "",
        python_version: "",
        description: "Interaction roundtrip IPC validation",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Integration: JSON-RPC roundtrip determinism",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp076",
        python_script: "",
        python_version: "",
        description: "Full pipeline scenario composition",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: end-to-end pipeline scenario (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp088",
        python_script: "",
        python_version: "",
        description: "Unified dashboard visualization",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: unified dashboard (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp089",
        python_script: "",
        python_version: "",
        description: "Patient explorer interactive demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: interactive patient explorer (no validation targets)",
    },
    // QS / Real-Data / WFDB experiments
    ProvenanceRecord {
        track: "microbiome",
        experiment: "exp107",
        python_script: "",
        python_version: "",
        description: "QS-augmented Anderson localization",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: QS gene profile → Anderson disorder coupling",
    },
    ProvenanceRecord {
        track: "microbiome",
        experiment: "exp108",
        python_script: "",
        python_version: "",
        description: "Real 16S Anderson diversity (HMP/Schubert public data)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "HMP2 16S (SRA: PRJNA275349); Schubert 2014 mBio 5:e01021-14",
    },
    ProvenanceRecord {
        track: "biosignal",
        experiment: "exp109",
        python_script: "",
        python_version: "",
        description: "MIT-BIH arrhythmia WFDB validation",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "MIT-BIH Arrhythmia Database (PhysioNet DOI:10.13026/C2F305)",
    },
    ProvenanceRecord {
        track: "comparative",
        experiment: "exp110",
        python_script: "",
        python_version: "",
        description: "Equine laminitis PK model",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: equine NSAID PK and laminitis biomarkers",
    },
    // NLME / Pipeline
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp075",
        python_script: "",
        python_version: "",
        description: "NLME cross-validation (FOCE/SAEM parameter recovery)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: NLME parameter recovery against known population PK model",
    },
];
