// SPDX-License-Identifier: AGPL-3.0-or-later
//! Provenance records for composition validation experiments (Tier 4–5, exp112–123).

use super::ProvenanceRecord;

pub(super) const RECORDS: &[ProvenanceRecord] = &[
    ProvenanceRecord {
        track: "validation",
        experiment: "exp112",
        python_script: "",
        python_version: "",
        description: "Composition validation: PK/PD dispatch parity",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: dispatch_science vs direct Rust call determinism",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp113",
        python_script: "",
        python_version: "",
        description: "Composition validation: microbiome dispatch parity",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: dispatch_science vs direct Rust call determinism",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp114",
        python_script: "",
        python_version: "",
        description: "Composition validation: health triad + registry surface",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: registered_capabilities coverage and dispatch completeness",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp115",
        python_script: "",
        python_version: "",
        description: "Composition validation: proto-nucleate alignment",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: socket conventions, capability list, PRIMAL_NAME/DOMAIN",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp116",
        python_script: "",
        python_version: "",
        description: "Composition validation: provenance session lifecycle",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: data session begin/record/complete + trio probe",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp117",
        python_script: "",
        python_version: "",
        description: "Composition validation: IPC round-trip + proto-nucleate alias fidelity",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: JSON-RPC wire protocol round-trip determinism",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp118",
        python_script: "",
        python_version: "",
        description: "Composition validation: deploy graph vs proto-nucleate alignment (Tier 5)",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-11",
        exact_command: "",
        baseline_source: "Composition: TOML graph structure, fragments, bonding, capability coverage",
    },
    ProvenanceRecord {
        track: "composition",
        experiment: "exp119",
        python_script: "",
        python_version: "",
        description: "Composition parity: live IPC science dispatch vs local Rust (Tier 4)",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-17",
        exact_command: "",
        baseline_source: "Composition: IPC JSON-RPC results vs direct Rust function calls",
    },
    ProvenanceRecord {
        track: "composition",
        experiment: "exp120",
        python_script: "",
        python_version: "",
        description: "Composition provenance: live trio round-trip via IPC (Tier 4)",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-17",
        exact_command: "",
        baseline_source: "Composition: provenance trio session lifecycle over IPC",
    },
    ProvenanceRecord {
        track: "composition",
        experiment: "exp121",
        python_script: "",
        python_version: "",
        description: "Composition health triad: liveness/readiness/capability.list via IPC (Tier 4)",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-17",
        exact_command: "",
        baseline_source: "Composition: NUCLEUS health probes over live JSON-RPC",
    },
    ProvenanceRecord {
        track: "composition",
        experiment: "exp122",
        python_script: "",
        python_version: "",
        description: "Level 5 primal proof: barraCuda ecobin IPC vs library parity (stats.mean, stats.std_dev, rng.uniform)",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-17",
        exact_command: "",
        baseline_source: "Primal proof: barraCuda wire-ready methods over JSON-RPC UDS",
    },
    ProvenanceRecord {
        track: "composition",
        experiment: "exp123",
        python_script: "",
        python_version: "",
        description: "NUCLEUS composition parity: full Tower+Node+Nest+cross-atomic pipeline for health niche",
        checks: 0,
        git_commit: "",
        run_date: "2026-05-08",
        exact_command: "",
        baseline_source: "Composition: full NUCLEUS parity (exp094 replication for healthSpring niche)",
    },
];
