// SPDX-License-Identifier: AGPL-3.0-or-later
//! Provenance registry: enumerates all Python control scripts in `control/`.
//!
//! This is the data layer — one entry per Python baseline script.
//! See [`super::ProvenanceRecord`] for the record type.
//!
//! **Rationale for single-file layout**: This file is a static data table
//! (no logic, no control flow). Splitting 54 entries across 10 track files
//! adds indirection without reducing complexity. The track-aware accessors
//! below provide the ergonomics of per-track modules without the overhead.

use super::ProvenanceRecord;

/// Well-known track identifiers used in the registry.
pub mod tracks {
    /// PK/PD (pharmacokinetics/pharmacodynamics).
    pub const PKPD: &str = "pkpd";
    /// Microbiome (diversity, SCFA, beta-diversity).
    pub const MICROBIOME: &str = "microbiome";
    /// Biosignal (ECG, HRV, beat classification).
    pub const BIOSIGNAL: &str = "biosignal";
    /// Endocrine (hormones, diurnal rhythms, HPA axis).
    pub const ENDOCRINE: &str = "endocrine";
    /// Comparative (cross-species PK, allometry).
    pub const COMPARATIVE: &str = "comparative";
    /// Discovery (localization, spectral, material).
    pub const DISCOVERY: &str = "discovery";
    /// Validation (cross-validate harness).
    pub const VALIDATION: &str = "validation";
    /// Scripts (utility scripts).
    pub const SCRIPTS: &str = "scripts";
    /// Toxicology (dose-response, hormesis).
    pub const TOXICOLOGY: &str = "toxicology";
    /// Simulation (mechanistic models).
    pub const SIMULATION: &str = "simulation";
}

/// Iterate over records belonging to a specific track.
pub fn records_for_track(track: &str) -> impl Iterator<Item = &'static ProvenanceRecord> {
    PROVENANCE_REGISTRY.iter().filter(move |r| r.track == track)
}

/// Look up a single record by experiment id (e.g. `"exp001"`).
#[must_use]
pub fn record_for_experiment(experiment: &str) -> Option<&'static ProvenanceRecord> {
    PROVENANCE_REGISTRY
        .iter()
        .find(|r| r.experiment == experiment)
}

/// Distinct track names present in the registry.
#[must_use]
pub fn distinct_tracks() -> Vec<&'static str> {
    let mut seen = Vec::new();
    for r in PROVENANCE_REGISTRY {
        if !seen.contains(&r.track) {
            seen.push(r.track);
        }
    }
    seen
}

/// Registry of all Python control scripts in `control/`.
///
/// Used to verify that every `.py` file in `control/` has a corresponding
/// entry. Run `cargo test registry_complete` to validate.
pub const PROVENANCE_REGISTRY: &[ProvenanceRecord] = &[
    // Track 1: PK/PD
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp001",
        python_script: "control/pkpd/exp001_hill_dose_response.py",
        python_version: "3.10+",
        description: "Hill dose-response 4-parameter IC50/EC50 for JAK inhibitors",
        checks: 8,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/pkpd/exp001_hill_dose_response.py",
        baseline_source: "Hill 1910 J Physiol doi:10.1113/jphysiol.1910.sp001397",
    },
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp002",
        python_script: "control/pkpd/exp002_one_compartment_pk.py",
        python_version: "3.10+",
        description: "One-compartment PK: IV bolus, oral absorption, AUC, Cmax, Tmax",
        checks: 12,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/pkpd/exp002_one_compartment_pk.py",
        baseline_source: "Rowland & Tozer, Clinical Pharmacokinetics (C0=Dose/Vd, oral Bateman function)",
    },
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp003",
        python_script: "control/pkpd/exp003_two_compartment_pk.py",
        python_version: "3.10+",
        description: "Two-compartment PK model (IV bolus)",
        checks: 16,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/pkpd/exp003_two_compartment_pk.py",
        baseline_source: "Gibaldi & Perrier, Pharmacokinetics 2nd Ed (two-compartment identities)",
    },
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp004",
        python_script: "control/pkpd/exp004_mab_pk_transfer.py",
        python_version: "3.10+",
        description: "mAb PK cross-species transfer (lokivetmab → nemolizumab/dupilumab)",
        checks: 13,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/pkpd/exp004_mab_pk_transfer.py",
        baseline_source: "Mahmood 2006 J Pharm Sci 95:1810 doi:10.1002/jps.20590 (allometric CL ∝ BW^0.75)",
    },
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp005",
        python_script: "control/pkpd/exp005_population_pk.py",
        python_version: "3.10+",
        description: "Population PK Monte Carlo with IIV",
        checks: 12,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/pkpd/exp005_population_pk.py",
        baseline_source: "Sheiner & Beal 1980 J Pharmacokinet Biopharm (population PK with IIV)",
    },
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp006",
        python_script: "control/pkpd/exp006_pbpk_compartments.py",
        python_version: "3.10+",
        description: "PBPK 5-tissue compartments (liver, kidney, muscle, fat, rest)",
        checks: 13,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/pkpd/exp006_pbpk_compartments.py",
        baseline_source: "Nestorov 2003 Clin Pharmacokinet 42:883 (PBPK tissue partition)",
    },
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp077",
        python_script: "control/pkpd/exp077_michaelis_menten_pk.py",
        python_version: "3.10+",
        description: "Michaelis-Menten nonlinear PK (phenytoin-like)",
        checks: 12,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/pkpd/exp077_michaelis_menten_pk.py",
        baseline_source: "Michaelis & Menten 1913 Biochem Z 49:333 (nonlinear saturation kinetics)",
    },
    ProvenanceRecord {
        track: "pkpd",
        experiment: "cross_validate",
        python_script: "control/pkpd/cross_validate.py",
        python_version: "3.10+",
        description: "Cross-validation: Python baseline JSON self-consistency",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/pkpd/cross_validate.py",
        baseline_source: "Self-consistency: Python baseline JSON round-trip",
    },
    // Track 2: Microbiome
    ProvenanceRecord {
        track: "microbiome",
        experiment: "exp010",
        python_script: "control/microbiome/exp010_diversity_indices.py",
        python_version: "3.10+",
        description: "Shannon, Simpson, Pielou, Chao1 diversity indices",
        checks: 15,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-08",
        exact_command: "python3 control/microbiome/exp010_diversity_indices.py",
        baseline_source: "Shannon 1948 doi:10.1002/j.1538-7305.1948.tb01338.x; Anderson 1958 doi:10.1103/PhysRev.109.1492",
    },
    ProvenanceRecord {
        track: "microbiome",
        experiment: "exp011",
        python_script: "control/microbiome/exp011_anderson_gut_lattice.py",
        python_version: "3.10+",
        description: "Anderson localization in 1D gut microbiome lattice",
        checks: 14,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-08",
        exact_command: "python3 control/microbiome/exp011_anderson_gut_lattice.py",
        baseline_source: "Anderson 1958 Phys Rev doi:10.1103/PhysRev.109.1492",
    },
    ProvenanceRecord {
        track: "microbiome",
        experiment: "exp012",
        python_script: "control/microbiome/exp012_cdiff_resistance.py",
        python_version: "3.10+",
        description: "C. difficile colonization resistance score",
        checks: 11,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-08",
        exact_command: "python3 control/microbiome/exp012_cdiff_resistance.py",
        baseline_source: "Shannon 1948 + Anderson 1958 (diversity → disorder → C. diff resistance)",
    },
    ProvenanceRecord {
        track: "microbiome",
        experiment: "exp013",
        python_script: "control/microbiome/exp013_fmt_rcdi.py",
        python_version: "3.10+",
        description: "FMT for recurrent C. diff infection (rCDI)",
        checks: 12,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-08",
        exact_command: "python3 control/microbiome/exp013_fmt_rcdi.py",
        baseline_source: "Kassam 2013 Am J Gastroenterol 108:500 (FMT for rCDI)",
    },
    ProvenanceRecord {
        track: "microbiome",
        experiment: "exp078",
        python_script: "control/microbiome/exp078_antibiotic_perturbation.py",
        python_version: "3.10+",
        description: "Antibiotic perturbation recovery (Shannon diversity)",
        checks: 10,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/microbiome/exp078_antibiotic_perturbation.py",
        baseline_source: "Dethlefsen & Relman 2011 PNAS 108:4554 (antibiotic perturbation recovery)",
    },
    ProvenanceRecord {
        track: "microbiome",
        experiment: "exp079",
        python_script: "control/microbiome/exp079_scfa_production.py",
        python_version: "3.10+",
        description: "SCFA production (Michaelis-Menten fermentation)",
        checks: 10,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/microbiome/exp079_scfa_production.py",
        baseline_source: "Morrison & Preston 2016 Gut Microbes 7:189 (SCFA fermentation kinetics)",
    },
    ProvenanceRecord {
        track: "microbiome",
        experiment: "exp080",
        python_script: "control/microbiome/exp080_gut_brain_serotonin.py",
        python_version: "3.10+",
        description: "Gut-brain serotonin pathway (diversity → tryptophan)",
        checks: 12,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/microbiome/exp080_gut_brain_serotonin.py",
        baseline_source: "O'Mahony 2015 Behav Brain Res 277:32 (gut-brain serotonin axis)",
    },
    // Track 3: Biosignal
    ProvenanceRecord {
        track: "biosignal",
        experiment: "exp020",
        python_script: "control/biosignal/exp020_pan_tompkins_qrs.py",
        python_version: "3.10+",
        description: "Pan-Tompkins QRS detection in ECG",
        checks: 12,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/biosignal/exp020_pan_tompkins_qrs.py",
        baseline_source: "Pan & Tompkins 1985 IEEE Trans Biomed Eng",
    },
    ProvenanceRecord {
        track: "biosignal",
        experiment: "exp021",
        python_script: "control/biosignal/exp021_hrv_metrics.py",
        python_version: "3.10+",
        description: "HRV metrics (RMSSD, pNN50, SDNN)",
        checks: 14,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/biosignal/exp021_hrv_metrics.py",
        baseline_source: "Task Force 1996 Circulation 93:1043 (HRV standards of measurement)",
    },
    ProvenanceRecord {
        track: "biosignal",
        experiment: "exp022",
        python_script: "control/biosignal/exp022_ppg_spo2.py",
        python_version: "3.10+",
        description: "PPG SpO2 R-value calibration",
        checks: 12,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/biosignal/exp022_ppg_spo2.py",
        baseline_source: "Mengelkoch 1994 (PPG R-value calibration: SpO2 = 110 - 25R)",
    },
    ProvenanceRecord {
        track: "biosignal",
        experiment: "exp023",
        python_script: "control/biosignal/exp023_fusion.py",
        python_version: "3.10+",
        description: "Multi-channel biosignal fusion (ECG + PPG + EDA)",
        checks: 15,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/biosignal/exp023_fusion.py",
        baseline_source: "Analytical fusion composite (weighted multi-modal biosignal index)",
    },
    ProvenanceRecord {
        track: "biosignal",
        experiment: "exp081",
        python_script: "control/biosignal/exp081_eda_stress.py",
        python_version: "3.10+",
        description: "EDA autonomic stress detection",
        checks: 11,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/biosignal/exp081_eda_stress.py",
        baseline_source: "Boucsein 2012 Electrodermal Activity (EDA stress detection)",
    },
    ProvenanceRecord {
        track: "biosignal",
        experiment: "exp082",
        python_script: "control/biosignal/exp082_arrhythmia_classification.py",
        python_version: "3.10+",
        description: "Arrhythmia beat classification (Normal, PVC, PAC)",
        checks: 12,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/biosignal/exp082_arrhythmia_classification.py",
        baseline_source: "MIT-BIH Arrhythmia Database (Moody & Mark 2001 IEEE Eng Med Biol 20:45)",
    },
    // Track 4: Endocrine
    ProvenanceRecord {
        track: "endocrine",
        experiment: "exp030",
        python_script: "control/endocrine/exp030_testosterone_im_pk.py",
        python_version: "3.10+",
        description: "Testosterone IM injection PK (cypionate depot)",
        checks: 12,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/endocrine/exp030_testosterone_im_pk.py",
        baseline_source: "Bhasin 2010 JCEM 95:2536 (testosterone cypionate IM depot PK)",
    },
    ProvenanceRecord {
        track: "endocrine",
        experiment: "exp031",
        python_script: "control/endocrine/exp031_testosterone_pellet_pk.py",
        python_version: "3.10+",
        description: "Testosterone pellet depot PK (zero-order release)",
        checks: 11,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/endocrine/exp031_testosterone_pellet_pk.py",
        baseline_source: "Pastuszak 2012 J Sex Med 9:1175 (testosterone pellet PK)",
    },
    ProvenanceRecord {
        track: "endocrine",
        experiment: "exp032",
        python_script: "control/endocrine/exp032_age_testosterone_decline.py",
        python_version: "3.10+",
        description: "Age-related testosterone decline (Harman 2001)",
        checks: 8,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/endocrine/exp032_age_testosterone_decline.py",
        baseline_source: "Harman et al. 2001 JCEM doi:10.1210/jcem.86.2.7219",
    },
    ProvenanceRecord {
        track: "endocrine",
        experiment: "exp033",
        python_script: "control/endocrine/exp033_trt_weight_trajectory.py",
        python_version: "3.10+",
        description: "TRT metabolic response: weight/waist trajectory",
        checks: 7,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/endocrine/exp033_trt_weight_trajectory.py",
        baseline_source: "Saad 2016 Obes Facts 9:373 (TRT weight/waist trajectory)",
    },
    ProvenanceRecord {
        track: "endocrine",
        experiment: "exp034",
        python_script: "control/endocrine/exp034_trt_cardiovascular.py",
        python_version: "3.10+",
        description: "TRT cardiovascular response (LDL, HDL, CRP, BP)",
        checks: 14,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/endocrine/exp034_trt_cardiovascular.py",
        baseline_source: "Corona 2011 JCEM 96:2341 (TRT cardiovascular endpoints)",
    },
    ProvenanceRecord {
        track: "endocrine",
        experiment: "exp035",
        python_script: "control/endocrine/exp035_trt_diabetes.py",
        python_version: "3.10+",
        description: "TRT and Type 2 diabetes (HbA1c, HOMA-IR)",
        checks: 10,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/endocrine/exp035_trt_diabetes.py",
        baseline_source: "Dhindsa 2016 Diabetes Care 39:S115 (TRT and T2DM HbA1c)",
    },
    ProvenanceRecord {
        track: "endocrine",
        experiment: "exp036",
        python_script: "control/endocrine/exp036_population_trt_montecarlo.py",
        python_version: "3.10+",
        description: "Population TRT Monte Carlo (10K virtual patients)",
        checks: 10,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/endocrine/exp036_population_trt_montecarlo.py",
        baseline_source: "Monte Carlo with log-normal IIV (population TRT Sheiner-style)",
    },
    ProvenanceRecord {
        track: "endocrine",
        experiment: "exp037",
        python_script: "control/endocrine/exp037_testosterone_gut_axis.py",
        python_version: "3.10+",
        description: "Testosterone-gut axis: microbiome stratification",
        checks: 10,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/endocrine/exp037_testosterone_gut_axis.py",
        baseline_source: "Tremellen 2012 Andrologia 44:439 (testosterone-gut microbiome axis)",
    },
    ProvenanceRecord {
        track: "endocrine",
        experiment: "exp038",
        python_script: "control/endocrine/exp038_hrv_trt_cardiovascular.py",
        python_version: "3.10+",
        description: "HRV × TRT cardiovascular cross-track",
        checks: 10,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/endocrine/exp038_hrv_trt_cardiovascular.py",
        baseline_source: "Cross-track: HRV (Task Force 1996) × TRT cardiovascular (Corona 2011)",
    },
    // Track 5: Comparative
    ProvenanceRecord {
        track: "comparative",
        experiment: "exp100",
        python_script: "control/comparative/exp100_canine_il31.py",
        python_version: "3.10+",
        description: "Canine IL-31 serum kinetics in atopic dermatitis",
        checks: 14,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/comparative/exp100_canine_il31.py",
        baseline_source: "Gonzales 2013 Vet Dermatol 24:48 doi:10.1111/j.1365-3164.2012.01098.x; Gonzales 2016 Vet Dermatol 27:34 (VAS EC50)",
    },
    ProvenanceRecord {
        track: "comparative",
        experiment: "exp101",
        python_script: "control/comparative/exp101_canine_jak1.py",
        python_version: "3.10+",
        description: "Canine oclacitinib JAK1 selectivity validation",
        checks: 15,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/comparative/exp101_canine_jak1.py",
        baseline_source: "Gonzales 2014 JVPT 37:317; ChEMBL JAK panel (oclacitinib 10 nM JAK1)",
    },
    ProvenanceRecord {
        track: "comparative",
        experiment: "exp102",
        python_script: "control/comparative/exp102_il31_pruritus_timecourse.py",
        python_version: "3.10+",
        description: "IL-31 pruritus time-course baseline",
        checks: 13,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/comparative/exp102_il31_pruritus_timecourse.py",
        baseline_source: "Gonzales 2016 Vet Dermatol 27:34 (pruritus VAS time-course)",
    },
    ProvenanceRecord {
        track: "comparative",
        experiment: "exp103",
        python_script: "control/comparative/exp103_lokivetmab_duration.py",
        python_version: "3.10+",
        description: "Lokivetmab dose-duration baseline",
        checks: 15,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/comparative/exp103_lokivetmab_duration.py",
        baseline_source: "Fleck/Gonzales 2021 Vet Dermatol 32:681 (~14d at 0.5 mg/kg, threshold ~3 µg/mL)",
    },
    ProvenanceRecord {
        track: "comparative",
        experiment: "exp104",
        python_script: "control/comparative/exp104_cross_species_pk.py",
        python_version: "3.10+",
        description: "Cross-species allometric PK scaling",
        checks: 15,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/comparative/exp104_cross_species_pk.py",
        baseline_source: "Mahmood 2006 J Pharm Sci 95:1810 doi:10.1002/jps.20590 (CL ∝ BW^0.75)",
    },
    ProvenanceRecord {
        track: "comparative",
        experiment: "exp105",
        python_script: "control/comparative/exp105_canine_gut_anderson.py",
        python_version: "3.10+",
        description: "Canine gut Anderson diversity baseline",
        checks: 13,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/comparative/exp105_canine_gut_anderson.py",
        baseline_source: "Shannon 1948 + Anderson 1958 (evenness → disorder → ξ)",
    },
    ProvenanceRecord {
        track: "comparative",
        experiment: "exp106",
        python_script: "control/comparative/exp106_feline_hyperthyroid.py",
        python_version: "3.10+",
        description: "Feline hyperthyroidism methimazole PK baseline",
        checks: 14,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/comparative/exp106_feline_hyperthyroid.py",
        baseline_source: "Trepanier 2006 JVIM 20:18 (methimazole MM PK, T4 response)",
    },
    // Track 6: Discovery
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp090",
        python_script: "control/discovery/exp090_matrix_scoring.py",
        python_version: "3.10+",
        description: "Anderson-augmented MATRIX drug repurposing scoring",
        checks: 15,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp090_matrix_scoring.py",
        baseline_source: "Fajgenbaum DC et al. NEJM 379:1941 (MATRIX pathway × geometry × disorder)",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp091",
        python_script: "control/discovery/exp091_addrc_hts.py",
        python_version: "3.10+",
        description: "ADDRC high-throughput screening analysis (Z', SSMD)",
        checks: 12,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp091_addrc_hts.py",
        baseline_source: "Zhang 1999 J Biomol Screen 4:67 doi:10.1177/108705719900400206 (Z'-factor); SSMD",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp092",
        python_script: "control/discovery/exp092_compound_library.py",
        python_version: "3.10+",
        description: "ADDRC compound library batch IC50 profiling",
        checks: 12,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp092_compound_library.py",
        baseline_source: "Hill 1910 J Physiol doi:10.1113/jphysiol.1910.sp001397 (IC50, selectivity index)",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp093",
        python_script: "control/discovery/exp093_chembl_jak_panel.py",
        python_version: "3.10+",
        description: "ChEMBL JAK inhibitor selectivity panel",
        checks: 15,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp093_chembl_jak_panel.py",
        baseline_source: "ChEMBL database; oclacitinib/tofacitinib/ruxolitinib/baricitinib IC50s",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp094",
        python_script: "control/discovery/exp094_rho_mrtf_fibrosis.py",
        python_version: "3.10+",
        description: "Rho/MRTF/SRF fibrosis scoring baseline",
        checks: 14,
        git_commit: "1e7c55f7056c3e4e7179f25ebd5d0eab8ce3b7a4",
        run_date: "2026-03-16",
        exact_command: "python3 control/discovery/exp094_rho_mrtf_fibrosis.py",
        baseline_source: "Haak 2014 JPET 349:480 doi:10.1124/jpet.114.213520 (CCG-1423, CCG-203971)",
    },
    // Track 7: Validation
    ProvenanceRecord {
        track: "validation",
        experiment: "exp040",
        python_script: "control/validation/exp040_barracuda_cpu.py",
        python_version: "3.10+",
        description: "barraCuda CPU parity analytical baselines",
        checks: 15,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/validation/exp040_barracuda_cpu.py",
        baseline_source: "Analytical identities (Hill, AUC, diversity, C0=Dose/Vd)",
    },
    // Track 8: Scripts
    ProvenanceRecord {
        track: "scripts",
        experiment: "bench_barracuda",
        python_script: "control/scripts/bench_barracuda_cpu_vs_python.py",
        python_version: "3.10+",
        description: "barraCuda CPU vs Python benchmark timing",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/scripts/bench_barracuda_cpu_vs_python.py",
        baseline_source: "Benchmark timing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "bench_v16",
        python_script: "control/scripts/bench_v16_cpu_vs_python.py",
        python_version: "3.10+",
        description: "V16 CPU parity benchmarks (Python baseline)",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/scripts/bench_v16_cpu_vs_python.py",
        baseline_source: "Benchmark timing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "compare_v16",
        python_script: "control/scripts/compare_v16_benchmarks.py",
        python_version: "3.10+",
        description: "Rust CPU vs Python benchmark comparison",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/scripts/compare_v16_benchmarks.py",
        baseline_source: "Benchmark comparison (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp085",
        python_script: "control/scripts/control_exp085_gpu_scaling.py",
        python_version: "3.10+",
        description: "GPU scaling validation (Python control)",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/scripts/control_exp085_gpu_scaling.py",
        baseline_source: "GPU scaling validation (Amdahl/Gustafson theoretical bounds)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "tolerances",
        python_script: "control/tolerances.py",
        python_version: "3.10+",
        description: "Centralized tolerance constants (Python mirror of tolerances.rs)",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/tolerances.py",
        baseline_source: "Tolerance constant definitions (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "update_provenance",
        python_script: "control/update_provenance.py",
        python_version: "3.10+",
        description: "Update baseline JSON files with provenance metadata",
        checks: 0,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/update_provenance.py",
        baseline_source: "Metadata utility (no validation targets)",
    },
    // Track 9: Low-Affinity Binding / Toxicology / Simulation
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp097",
        python_script: "control/discovery/exp097_affinity_landscape.py",
        python_version: "3.10+",
        description: "Low-affinity binding: composite score, selectivity, Gini breadth",
        checks: 18,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/discovery/exp097_affinity_landscape.py",
        baseline_source: "Hill 1910 (fractional occupancy); Lorenz/Gini (inequality metrics)",
    },
    ProvenanceRecord {
        track: "toxicology",
        experiment: "exp098",
        python_script: "control/toxicology/exp098_toxicity_landscape.py",
        python_version: "3.10+",
        description: "Toxicity landscape: systemic burden, IPR, clearance, delocalization",
        checks: 15,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/toxicology/exp098_toxicity_landscape.py",
        baseline_source: "Anderson 1958 (IPR/localization); Rowland & Tozer (clearance kinetics)",
    },
    ProvenanceRecord {
        track: "toxicology",
        experiment: "exp099",
        python_script: "control/toxicology/exp099_hormesis.py",
        python_version: "3.10+",
        description: "Hormesis: biphasic dose-response, mithridatism, caloric restriction",
        checks: 27,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/toxicology/exp099_hormesis.py",
        baseline_source: "Calabrese & Baldwin 2003 (hormesis); Mattson & Calabrese 2010",
    },
    ProvenanceRecord {
        track: "simulation",
        experiment: "exp111",
        python_script: "control/simulation/exp111_causal_terrarium.py",
        python_version: "3.10+",
        description: "Causal terrarium: mechanistic fitness, population dynamics, ecosystem",
        checks: 18,
        git_commit: "56c5b2c8756a870d200dacda5a91af223fbbc2d6",
        run_date: "2026-03-19",
        exact_command: "python3 control/simulation/exp111_causal_terrarium.py",
        baseline_source: "Lotka-Volterra (population dynamics); HSP/SOD/p53/mTOR (pathway biology)",
    },
    // ── Diagnostic / Clinical Pipeline (Rust analytical — no Python control) ──
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp050",
        python_script: "",
        python_version: "",
        description: "Diagnostic pipeline: patient assessment → composite risk",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: ValidationHarness checks against lib-computed values",
    },
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp051",
        python_script: "",
        python_version: "",
        description: "Population diagnostic Monte Carlo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: population statistics against bounded ranges",
    },
    // ── GPU / Compute Experiments (bench/parity — no Python baseline) ──
    ProvenanceRecord {
        track: "validation",
        experiment: "exp053",
        python_script: "",
        python_version: "",
        description: "GPU parity: Hill/PopPK/Diversity CPU vs GPU",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU fallback as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp054",
        python_script: "",
        python_version: "",
        description: "GPU fused pipeline validation",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU sequential as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp055",
        python_script: "",
        python_version: "",
        description: "GPU scaling validation (Amdahl/Gustafson bounds)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Theoretical: Amdahl's law + Gustafson's law scaling bounds",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp060",
        python_script: "",
        python_version: "",
        description: "CPU vs GPU pipeline comparative benchmark",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU path as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp062",
        python_script: "",
        python_version: "",
        description: "PCIe transfer validation (bandwidth bounds)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Theoretical: PCIe Gen3/4/5 bandwidth limits",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp067",
        python_script: "",
        python_version: "",
        description: "GPU parity extended (V16 trio + Tier B ops)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU fallback as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp083",
        python_script: "",
        python_version: "",
        description: "GPU V16 parity (MM/SCFA/BeatClassify CPU vs GPU)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "GPU parity: CPU fallback as gold standard",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp084",
        python_script: "",
        python_version: "",
        description: "V16 CPU parity benchmarks",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Benchmark: CPU timing comparison (no validation targets)",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp086",
        python_script: "",
        python_version: "",
        description: "ToadStool V16 dispatch matrix",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Integration: toadStool compute.dispatch.submit round-trip",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp087",
        python_script: "",
        python_version: "",
        description: "Mixed NUCLEUS V16 dispatch (CPU+GPU+NPU)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Integration: metalForge substrate selection + dispatch",
    },
    // ── IPC / Dashboard / Visualization (demo — no Python baseline) ──
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp052",
        python_script: "",
        python_version: "",
        description: "petalTongue render integration demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: petalTongue visualization.render IPC (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp056",
        python_script: "",
        python_version: "",
        description: "Study scenario dump for whitePaper baseCamp",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: scenario generation (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp061",
        python_script: "",
        python_version: "",
        description: "Mixed hardware dispatch demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: metalForge hardware dispatch (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp063",
        python_script: "",
        python_version: "",
        description: "Clinical TRT scenario explorer",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: clinical scenario generation (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp064",
        python_script: "",
        python_version: "",
        description: "IPC push integration demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: petalTongue IPC push (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp065",
        python_script: "",
        python_version: "",
        description: "Live dashboard visualization demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: live scenario dashboard (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp066",
        python_script: "",
        python_version: "",
        description: "barraCuda CPU benchmark suite",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Benchmark: CPU timing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp068",
        python_script: "",
        python_version: "",
        description: "GPU benchmark suite",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Benchmark: GPU timing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp069",
        python_script: "",
        python_version: "",
        description: "ToadStool dispatch matrix demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: toadStool dispatch routing (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp070",
        python_script: "",
        python_version: "",
        description: "PCIe P2P bypass validation",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Integration: PCIe P2P transfer (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp071",
        python_script: "",
        python_version: "",
        description: "Mixed system pipeline demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: multi-substrate pipeline (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp072",
        python_script: "",
        python_version: "",
        description: "Compute dashboard visualization",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: compute metrics dashboard (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp073",
        python_script: "",
        python_version: "",
        description: "Clinical TRT dashboard demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: TRT clinical dashboard (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp074",
        python_script: "",
        python_version: "",
        description: "Interaction roundtrip IPC validation",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Integration: JSON-RPC roundtrip determinism",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp076",
        python_script: "",
        python_version: "",
        description: "Full pipeline scenario composition",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: end-to-end pipeline scenario (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp088",
        python_script: "",
        python_version: "",
        description: "Unified dashboard visualization",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: unified dashboard (no validation targets)",
    },
    ProvenanceRecord {
        track: "scripts",
        experiment: "exp089",
        python_script: "",
        python_version: "",
        description: "Patient explorer interactive demo",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Demo: interactive patient explorer (no validation targets)",
    },
    // ── Discovery / Comparative (science with analytical baselines) ──
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp095",
        python_script: "",
        python_version: "",
        description: "iPSC skin model fibrosis scoring",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: fibrosis pathway geometry + Anderson disorder scoring",
    },
    ProvenanceRecord {
        track: "discovery",
        experiment: "exp096",
        python_script: "",
        python_version: "",
        description: "Niclosamide nanoparticle delivery model",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: drug delivery PK kinetics",
    },
    // ── QS / Real-Data / WFDB Experiments ──
    ProvenanceRecord {
        track: "microbiome",
        experiment: "exp107",
        python_script: "",
        python_version: "",
        description: "QS-augmented Anderson localization",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: QS gene profile → Anderson disorder coupling",
    },
    ProvenanceRecord {
        track: "microbiome",
        experiment: "exp108",
        python_script: "",
        python_version: "",
        description: "Real 16S Anderson diversity (HMP/Schubert public data)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "HMP2 16S (SRA: PRJNA275349); Schubert 2014 mBio 5:e01021-14",
    },
    ProvenanceRecord {
        track: "biosignal",
        experiment: "exp109",
        python_script: "",
        python_version: "",
        description: "MIT-BIH arrhythmia WFDB validation",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "MIT-BIH Arrhythmia Database (PhysioNet DOI:10.13026/C2F305)",
    },
    ProvenanceRecord {
        track: "comparative",
        experiment: "exp110",
        python_script: "",
        python_version: "",
        description: "Equine laminitis PK model",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: equine NSAID PK and laminitis biomarkers",
    },
    // ── NLME / Pipeline (science with analytical baselines) ──
    ProvenanceRecord {
        track: "pkpd",
        experiment: "exp075",
        python_script: "",
        python_version: "",
        description: "NLME cross-validation (FOCE/SAEM parameter recovery)",
        checks: 0,
        git_commit: "",
        run_date: "2026-03-19",
        exact_command: "",
        baseline_source: "Rust analytical: NLME parameter recovery against known population PK model",
    },
    // ── Composition Validation (Tier 4 — Rust dispatch parity) ──
    ProvenanceRecord {
        track: "validation",
        experiment: "exp112",
        python_script: "",
        python_version: "",
        description: "Composition validation: PK/PD dispatch parity",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: dispatch_science vs direct Rust call determinism",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp113",
        python_script: "",
        python_version: "",
        description: "Composition validation: microbiome dispatch parity",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: dispatch_science vs direct Rust call determinism",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp114",
        python_script: "",
        python_version: "",
        description: "Composition validation: health triad + registry surface",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: registered_capabilities coverage and dispatch completeness",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp115",
        python_script: "",
        python_version: "",
        description: "Composition validation: proto-nucleate alignment",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: socket conventions, capability list, PRIMAL_NAME/DOMAIN",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp116",
        python_script: "",
        python_version: "",
        description: "Composition validation: provenance session lifecycle",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: data session begin/record/complete + trio probe",
    },
    ProvenanceRecord {
        track: "validation",
        experiment: "exp117",
        python_script: "",
        python_version: "",
        description: "Composition validation: IPC round-trip + proto-nucleate alias fidelity",
        checks: 0,
        git_commit: "",
        run_date: "2026-04-10",
        exact_command: "",
        baseline_source: "Composition: JSON-RPC wire protocol round-trip determinism",
    },
];
